/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connection_PlayerServer_ConnectionThread */

#ifndef _Included_connection_PlayerServer_ConnectionThread
#define _Included_connection_PlayerServer_ConnectionThread
#ifdef __cplusplus
extern "C" {
#endif
#undef connection_PlayerServer_ConnectionThread_MIN_PRIORITY
#define connection_PlayerServer_ConnectionThread_MIN_PRIORITY 1L
#undef connection_PlayerServer_ConnectionThread_NORM_PRIORITY
#define connection_PlayerServer_ConnectionThread_NORM_PRIORITY 5L
#undef connection_PlayerServer_ConnectionThread_MAX_PRIORITY
#define connection_PlayerServer_ConnectionThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
