/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connection_PlayerServer */

#ifndef _Included_connection_PlayerServer
#define _Included_connection_PlayerServer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
